version: '3.8'

services:
  interview-summary:
    build: .
    container_name: interview-summary
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
      - ./results:/app/results
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1